# Stage 1: Build the application
# Using JDK 21 to match your project configuration
FROM gradle:8-jdk21 AS build
WORKDIR /home/gradle/src

# Copy only the files needed to pull dependencies (caching layer)
COPY --chown=gradle:gradle build.gradle.kts gradle.properties settings.gradle.kts /home/gradle/src/
# If you have a 'gradle' folder with the wrapper, include it
COPY --chown=gradle:gradle gradle /home/gradle/src/gradle

# This will download dependencies and cache them
RUN gradle dependencies --no-daemon

# Copy the rest of the source code
COPY --chown=gradle:gradle . /home/gradle/src

# Build the Fat JAR using the Ktor plugin task
RUN gradle buildFatJar --no-daemon

# Stage 2: Create the Runtime Image
# Using Corretto 21 for a slim, production-ready JRE
FROM amazoncorretto:21-alpine AS runtime

# Create a non-root user for security
RUN addgroup -S ktor && adduser -S ktor -G ktor
USER ktor

WORKDIR /app
EXPOSE 8080

# Copy the specific Fat JAR generated by the buildFatJar task
COPY --from=build /home/gradle/src/build/libs/ktor-sample-all.jar /app/ktor-app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "/app/ktor-app.jar"]